language: java
sudo: false
matrix:
  include:
    - jdk: openjdk8
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.2
      env: JAVA_HOME=$(/usr/libexec/java_home)
script: ./build.sh -Dexist.autodeploy=off -Dtest.haltonerror=true -Dtest.haltonfailure=true clean clean-all all test
notifications:
  hipchat: ec8fcfa661addc56a361a8ef536320@integrations
